const Categories = [
  Sarees = [
    {
      tittle: "Sarees",
      Image:
        "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/n/t/e/free-mk-zal-cosbila-fashion-unstitched-original-imagkuzjj9gwh6j6.jpeg?q=70",
      data: {
        Sarees: [
          {
            tittle: "Sarees",
            Image: [
              "https://rukminim1.flixcart.com/image/612/612/l4ln8nk0/sari/p/2/u/free-2535s934-samah-unstitched-original-imagfgq7pc2mc4vz.jpeg?q=70",
              "https://rukminim1.flixcart.com/image/612/612/k0lbdzk0pkrrdj/sari/b/b/u/yellow-momi-netal-designer-original-imaf66r4qfdvakth.jpeg?q=70",
              "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/j/u/u/free-embellished-sdk-fashion-unstitched-original-image9gppyg4ahyf.jpeg?q=70",
            ],
            SellingPrice: "2624",
            DiscountPrice: "975",
            DisPrsent: "62%",
            SoldBy: "shopeen",
            COD: "availble",
            Size: ["S", "M", "L", "XL", "XXL"],
            ProductDetails: {
              ProductCode: "SHSJMPA16",
              idealFor: "Women",
              packOf: "1",
              occasion: "party",
              Fabric: "Satain",
            },
            Status: "Stock",
            quenity: "1",
          },
        ],
        Sarees: [
          {
            tittle: "Sarees",
            Image: [
              "https://rukminim1.flixcart.com/image/612/612/knan98w0/sari/s/v/q/free-vs-507-1-leelavati-unstitched-original-imag2y9vgxpzme3j.jpeg?q=70",
              "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/n/w/w/free-embellished-sdk-fashion-unstitched-original-image9gp6yhyjyja.jpeg?q=70",
              "https://rukminim1.flixcart.com/image/612/612/k7c88sw0/sari/j/z/y/free-ladli-krishna-r-fashion-original-imafphxupazpggbj.jpeg?q=70",
            ],
            SellingPrice: "3024",
            DiscountPrice: "1375",
            DisPrsent: "60%",
            SoldBy: "shopeen",
            COD: "availble",
            Size: ["S", "M", "L", "XL", "XXL"],
            ProductDetails: {
              ProductCode: "SHSJMPA16",
              idealFor: "Women",
              packOf: "1",
              occasion: "Fastive",
              Fabric: "Satain",
            },
            Status: "InStock",
            quenity: "1",
          },
        ],
        Sarees: [
          {
            tittle: "Sarees",
            Image: [
              "https://rukminim1.flixcart.com/image/612/612/kirr24w0-0/sari/e/d/a/free-kavaya-kedar-fab-unstitched-original-imafyh8jm8gtpbst.jpeg?q=70",
              "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/w/5/n/free-pattu-saree-ejoty-fashion-unstitched-original-imag4abzywzyk5ry-bb.jpeg?q=70",
              "https://rukminim1.flixcart.com/image/612/612/kzvlua80/sari/7/s/l/free-sds0030-sadika-unstitched-original-imagbsg4na5x3gfn.jpeg?q=70",
            ],
            SellingPrice: "2446",
            DiscountPrice: "1100",
            DisPrsent: "56%",
            SoldBy: "shopeen",
            COD: "availble",
            Size: ["S", "M", "L", "XL", "XXL"],
            ProductDetails: {
              ProductCode: "SHSJMPA16",
              idealFor: "Women",
              packOf: "1",
              occasion: "FunctionWear",
              Fabric: "Satain",
            },
            Status: "Stock",
            quenity: "1",
          },
        ],
        BollywoodCollection: [
          {
            tittle: "BollywoodCollection",
            Image: [
              "https://rukminim1.flixcart.com/image/612/612/l3rmzrk0/sari/j/e/b/free-buti-aika-unstitched-original-imaget5hdhms65nq.jpeg?q=70",
              "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/a/b/d/free-rtw-gajari-aika-unstitched-original-imaghutaweytnxhd.jpeg?q=70",
              "https://rukminim1.flixcart.com/image/612/612/kr0ynbk0/sari/b/9/x/free-masala-grey-active-unstitched-original-imag4wsyfqzbaaf3.jpeg?q=70",
            ],
            SellingPrice: "2700",
            DiscountPrice: "1150",
            DisPrsent: "57%",
            SoldBy: "shopeen",
            COD: "availble",
            Size: ["S", "M", "L", "XL", "XXL"],
            ProductDetails: {
              ProductCode: "SHSJMPA16",
              idealFor: "Women",
              packOf: "1",
              occasion: "FunctionWear",
              Fabric: "Satain",
            },
            Status: "InStock",
            quenity: "1",
          },
        ],
        BollywoodCollection: [
          {
            tittle: "BollywoodCollection",
            Image: [
              "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/p/8/n/free-diwa-half-yellow-aika-unstitched-original-imaghg969ht3rpkk.jpeg?q=70",
              "https://rukminim1.flixcart.com/image/612/612/l3rmzrk0/sari/g/s/s/free-buti-aika-unstitched-original-imaget5hgzafzpqc.jpeg?q=70",
              "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/g/9/h/free-bahubali-gajari-dharam-fabrics-unstitched-original-imafyhjgvcmerbjp-bb.jpeg?q=70",
            ],
            SellingPrice: "2626",
            DiscountPrice: "950",
            DisPrsent: "63%",
            SoldBy: "shopeen",
            COD: "availble",
            Size: ["S", "M", "L", "XL", "XXL"],
            ProductDetails: {
              ProductCode: "SHSJMPA16",
              idealFor: "Women",
              packOf: "1",
              occasion: "FunctionWear",
              Fabric: "Satain",
            },
            Status: "InStock",
            quenity: "1",
          },
        ],
        BollywoodCollection: [
          {
            tittle: "BollywoodCollection",
            Image: [
              "https://rukminim1.flixcart.com/image/612/612/jxc5a4w0/sari/w/p/r/free-paper-batli-saree-collection-original-imafhtg3daydahp5.jpeg?q=70",
              "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/7/8/2/free-rtw-navy-saree-collection-unstitched-original-imaghutcwgyqn9pc.jpeg?q=70",
              "https://rukminim1.flixcart.com/image/612/612/k4hcjgw0pkrrdj/sari/z/q/d/free-red-aura-saree-red-apnisha-aura-saree-red-original-imaffwmuyryfaadz.jpeg?q=70",
            ],
            SellingPrice: "1799",
            DiscountPrice: "1061",
            DisPrsent: "41%",
            SoldBy: "shopeen",
            COD: "availble",
            Size: ["S", "M", "L", "XL", "XXL"],
            ProductDetails: {
              ProductCode: "SHSJMPA16",
              idealFor: "Women",
              packOf: "1",
              occasion: "FunctionWear",
              Fabric: "Satain",
            },
            Status: "InStock",
            quenity: "1",
          },
        ],
        PrintedSarees: [
          {
            tittle: "PrintedSarees",
            Image: [
              "https://rukminim1.flixcart.com/image/612/612/kxaq7ww0/sari/o/k/q/free-grey-1692-6-kashvi-sarees-unstitched-original-imag9s7ggsjw2gcn.jpeg?q=70",
              "https://rukminim1.flixcart.com/image/612/612/kwtkxow0/sari/2/a/z/free-looknbook-7045-peach-fabian-fashion-unstitched-original-imag9eztv86gbvfq.jpeg?q=70",
              "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/i/l/i/free-pzf-m-st-jasud-prkz-fashion-unstitched-original-imagjhnum9yfxswm.jpeg?q=70",
            ],
            SellingPrice: "1799",
            DiscountPrice: "590",
            DisPrsent: "67%",
            SoldBy: "shopeen",
            COD: "availble",
            Size: ["S", "M", "L", "XL", "XXL"],
            ProductDetails: {
              ProductCode: "SHSJMPA16",
              idealFor: "Women",
              packOf: "1",
              occasion: "FunctionWear",
              Fabric: "Satain",
            },
            Status: "InStock",
            quenity: "1",
          },
        ],
        PrintedSarees: [
          {
            tittle: "PrintedSarees",
            Image: [
              "https://rukminim1.flixcart.com/image/612/612/k6wiefk0/sari/g/x/k/free-trio-1285-1287-1301-kashvi-sarees-original-imafp8vqfky69ghq.jpeg?q=70",
              "https://rukminim1.flixcart.com/image/612/612/knan98w0/sari/s/v/q/free-vs-507-1-leelavati-unstitched-original-imag2y9vgxpzme3j.jpeg?q=70",
              "https://rukminim1.flixcart.com/image/612/612/kq2o2vk0/sari/g/g/c/free-grey-12023-laheja-unstitched-original-imag466sfndhzzxm.jpeg?q=70",
            ],
            SellingPrice: "2710",
            DiscountPrice: "835",
            DisPrsent: "69%",
            SoldBy: "shopeen",
            COD: "availble",
            Size: ["S", "M", "L", "XL", "XXL"],
            ProductDetails: {
              ProductCode: "SHSJMPA16",
              idealFor: "Women",
              packOf: "1",
              occasion: "FunctionWear",
              Fabric: "Satain",
            },
            Status: "InStock",
            quenity: "1",
          },
        ],
        PrintedSarees: [
          {
            tittle: "PrintedSarees",
            Image: [
              "https://rukminim1.flixcart.com/image/612/612/kq18n0w0/sari/v/0/w/free-25764-mirchi-fashion-unstitched-original-imag44twgjqfevyf.jpeg?q=70",
              "https://rukminim1.flixcart.com/image/612/612/k4ss2a80/sari/q/9/a/free-s181194-new-desirable-admirable-most-south-indian-bengali-original-imaf2yyqzestjazq.jpeg?q=70",
              "https://rukminim1.flixcart.com/image/612/612/kx25ksw0/sari/j/v/w/free-emv710-emv-unstitched-original-imag9hzsnwbtwabp.jpeg?q=70",
            ],
            SellingPrice: "1599",
            DiscountPrice: "658",
            DisPrsent: "58%",
            SoldBy: "shopeen",
            COD: "availble",
            Size: ["S", "M", "L", "XL", "XXL"],
            ProductDetails: {
              ProductCode: "SHSJMPA16",
              idealFor: "Women",
              packOf: "1",
              occasion: "FunctionWear",
              Fabric: "Satain",
            },
            Status: "InStock",
            quenity: "1",
          },
        ],
      },
    },
  ],
  Trousers = [
    {
      tittle: "Trousers",
      Image:
        "https://rukminim1.flixcart.com/image/612/612/xif0q/trouser/w/m/g/32-combo-15-31-sam-jack-original-imaga5h98knwmbtq-bb.jpeg?q=70",
      data: {
        Trousers: [
          {
            tittle: "Trousers",
            Image: [
              "https://rukminim1.flixcart.com/image/612/612/xif0q/trouser/v/h/c/40-combo-11-15-40-sam-jack-original-imag6gevhezhyy7d-bb.jpeg?q=70",
              "https://rukminim1.flixcart.com/image/612/612/xif0q/trouser/c/f/e/34-combo-30-32-sam-jack-original-imaga3gyqrvngtrg-bb.jpeg?q=70",
              "https://rukminim1.flixcart.com/image/612/612/kvvad8w0/trouser/i/g/t/38-31dsmg-38-sam-jack-original-imag8z9kahhahkdg.jpeg?q=70",
            ],
            SellingPrice: "1899",
            DiscountPrice: "900",
            DisPrsent: "49%",
            SoldBy: "shopeen",
            COD: "availble",
            Size: [28, 30, 32, 34, 36, 38, 40],
            ProductDetails: {
              ProductCode: "SHSJMPA16",
              idealFor: "Men",
              packOf: "1",
              occasion: "Marriage",
              Fabric: "Satain",
            },
            Status: "Stock",
            quenity: "1",
          },
        ],
      },

      Trousers: [
        {
          tittle: "Trousers",
          Image: [
            "https://rukminim1.flixcart.com/image/612/612/kt4ozgw0/trouser/5/f/s/36-combo-11-15-36-sam-jack-original-imag6jpvcvpyvqey.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/kt4ozgw0/trouser/9/f/e/32-combo-5dsbk-01-16dslg-01-32-sam-jack-original-imag6jpukyjmk7br.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/kkwwu4w0/trouser/g/a/p/28-kctr-frml-99-bk-fubar-original-imagy5yhmk3thkcj.jpeg?q=70",
          ],
          SellingPrice: "2099",
          DiscountPrice: "1100",
          DisPrsent: "52%",
          SoldBy: "shopeen",
          COD: "availble",
          Size: [28, 30, 32, 34, 36, 38],
          ProductDetails: {
            ProductCode: "SHSJMPA16",
            idealFor: "Men",
            packOf: "1",
            occasion: "party",
            Fabric: "Rayon",
          },
          Status: "Stock",
          quenity: "1",
        },
      ],

      Trousers: [
        {
          tittle: "Trousers",
          Image: [
            "https://rukminim1.flixcart.com/image/612/612/ku1k4280/trouser/a/l/1/38-p0amn119-tommy-hilfiger-original-imag792fzzdjhyyj.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/xif0q/trouser/r/j/f/28-kctr-frml-99-crm-fubar-original-imagy6g4tp3vcr4k-bb.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/xif0q/trouser/r/e/m/28-cyfor-a-cyphus-original-imag66aucwaygyqq-bb.jpeg?q=70",
          ],
          SellingPrice: "1699",
          DiscountPrice: "700",
          DisPrsent: "45%",
          SoldBy: "shopeen",
          COD: "availble",
          Size: [28, 30, 32, 34],
          ProductDetails: {
            ProductCode: "SHSJMPA16",
            idealFor: "Men",
            packOf: "1",
            occasion: "engagement",
            Fabric: "LycraBlend",
          },
          Status: "InStock",
          quenity: "1",
        },
      ],
      Jeans: [
        {
          tittle: "Jeans",
          Image: [
            "https://rukminim1.flixcart.com/image/612/612/xif0q/jean/l/s/f/-original-imaghv2uzwyvezcs.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/xif0q/jean/7/j/3/-original-imaggvukptb32btu.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/xif0q/jean/y/i/b/32-18298-1235-levi-s-original-imaggedgrtpmbnym.jpeg?q=70",
          ],
          SellingPrice: "1299",
          DiscountPrice: "499",
          DisPrsent: "61%",
          SoldBy: "shopeen",
          COD: "availble",
          Size: [28, 30, 32, 34],
          ProductDetails: {
            ProductCode: "SHSJMPA16",
            idealFor: "Men",
            packOf: "1",
            occasion: "party",
            Fabric: "LycraBlend",
          },
          Status: "InStock",
          quenity: "1",
        },
      ],
      Jeans: [
        {
          tittle: "Jeans",
          Image: [
            "https://rukminim1.flixcart.com/image/612/612/xif0q/jean/g/d/f/30-000897-highlander-original-imafpchpgqkjpuqg-bb.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/k70spzk0/jean/f/p/v/30-hljn000893-highlander-original-imafpchpu8dksxfc.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/xif0q/jean/h/y/d/28-1-eps-black-06-urbano-fashion-original-imafumyf4fxzhduu-bb.jpeg?q=70",
          ],
          SellingPrice: "1999",
          DiscountPrice: "759",
          DisPrsent: "62%",
          SoldBy: "shopeen",
          COD: "availble",
          Size: [28, 30, 32, 34],
          ProductDetails: {
            ProductCode: "SHSJMPA16",
            idealFor: "Men",
            packOf: "1",
            occasion: "eid al fitr",
            Fabric: "LycraBlend",
          },
          Status: "InStock",
          quenity: "1",
        },
      ],
      Jeans: [
        {
          tittle: "Jeans",
          Image: [
            "https://rukminim1.flixcart.com/image/612/612/xif0q/jean/t/e/6/32-suplpsjean-mblue-supernova-inc-original-imagm6rtjhgyhb3a.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/xif0q/jean/w/f/u/30-hljn000690-highlander-original-imafpchxfs6zzjyh-bb.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/k66sh3k0/jean/h/v/w/36-10046833-roadster-original-imafzpc3xv2emp5a.jpeg?q=70",
          ],
          SellingPrice: "1799",
          DiscountPrice: "989",
          DisPrsent: "45%",
          SoldBy: "shopeen",
          COD: "availble",
          Size: [28, 30, 32, 34],
          ProductDetails: {
            ProductCode: "SHSJMPA16",
            idealFor: "Men",
            packOf: "1",
            occasion: "engagement",
            Fabric: "formaljeans",
          },
          Status: "InStock",
          quenity: "1",
        },
      ],
      FormalPants: [
        {
          tittle: "FormalPants",
          Image: [
            "https://rukminim1.flixcart.com/image/612/612/ksgehzk0/trouser/k/2/q/32-cyfor-a-cyphus-original-imag6yyyedypgvke.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/xif0q/trouser/q/i/t/36-kctr-frml-99-nb-fubar-original-imagyzp8e35phtyt-bb.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/xif0q/trouser/v/w/w/28-kctr-frml-99-bk-fubar-original-imagy5yhbanbpwja-bb.jpeg?q=70",
          ],
          SellingPrice: "1199",
          DiscountPrice: "450",
          DisPrsent: "59%",
          SoldBy: "shopeen",
          COD: "availble",
          Size: [28, 30, 32, 34],
          ProductDetails: {
            ProductCode: "SHSJMPA16",
            idealFor: "Men",
            packOf: "1",
            occasion: "annual function",
            Fabric: "formalpants",
          },
          Status: "InStock",
          quenity: "1",
        },
      ],
      FormalPants: [
        {
          tittle: "FormalPants",
          Image: [
            "https://rukminim1.flixcart.com/image/612/612/xif0q/trouser/t/u/o/44-elan-single-elanhood-original-imag3ebdrdhb4vyh-bb.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/l45xea80/trouser/m/c/8/30-kctr-frml-99-stlg-fubar-original-imagf4jx6gjbm3zg.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/xif0q/trouser/y/o/i/32-cyfor-f-cyphus-original-imag6yzhz8kfsfpr-bb.jpeg?q=70",
          ],
          SellingPrice: "1899",
          DiscountPrice: "850",
          DisPrsent: "52%",
          SoldBy: "shopeen",
          COD: "availble",
          Size: [28, 30, 32, 34],
          ProductDetails: {
            ProductCode: "SHSJMPA16",
            idealFor: "Men",
            packOf: "1",
            occasion: "engagement",
            Fabric: "Lycra",
          },
          Status: "InStock",
          quenity: "1",
        },
      ],
      FormalPants: [
        {
          tittle: "FormalPants",
          Image: [
            "https://rukminim1.flixcart.com/image/612/612/xif0q/trouser/m/2/m/32-rmts04716-f2-raymond-original-imagn9mgtbyscmy6.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/kyt0ya80/trouser/k/s/b/30-kctr-frml-99-pcbl-fubar-original-imagayjrcnbqgeyq.jpeg?q=70",
            "https://rukminim1.flixcart.com/image/612/612/ksgehzk0/trouser/y/r/l/28-cyfor-c-cyphus-original-imag6yz54dsqfghh.jpeg?q=70",
          ],
          SellingPrice: "1899",
          DiscountPrice: "949",
          DisPrsent: "50%",
          SoldBy: "shopeen",
          COD: "availble",
          Size: [28, 30, 32, 34],
          ProductDetails: {
            ProductCode: "SHSJMPA16",
            idealFor: "Men",
            packOf: "1",
            occasion: "marriage",
            Fabric: "LycraBlend",
          },
          Status: "InStock",
          quenity: "1",
        },
      ],
    },
    ,
  ],
];

const FashionSareeCollections = [
  {
    title: "FashionSareeCollections",
    Productlist: [
      {
        title: "Unstitched Pure Silk Multi-purpose Fabric Self Design",
        Image: [
          "https://rukminim1.flixcart.com/image/832/832/l5bd5zk0/sari/e/7/w/free-ms-172-dark-blue-lifera-unstitched-original-imaggysn8wggvbx8.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/832/832/l5bd5zk0/sari/b/s/8/free-ms-172-dark-blue-lifera-unstitched-original-imaggysnjet8jatu.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/832/832/l5iid8w0/sari/i/x/g/free-mahadev-pandadi-mahadev-retail-shop-unstitched-original-imaggysnqbxzbghw.jpeg?q=70",
        ],
        sellingPrice: "2999",
        disPrice: "799",
        disPrsent: "73%",
        soldBy: "SHOPPEEN",
        COD: "Available",
        Status: "In-Stock",
        quantity: "1",
        Size: ["S", "M", "L", "XL", "XXL"],
        ProductDetails: {
          productCode: "SHSDDSAH1512A678",
          idealFor: "Women",
          packOf: "1",
          occasion: "Festive, Party wear",
          fabric: "JapanSilk",
        },
      },

      {
        title: "Embroidered Fashion Pure Silk Saree  (Blue)",
        Image: [
          "https://rukminim1.flixcart.com/image/832/832/k3hmj680/sari/z/q/j/free-10045-jimplei-original-imafmmy6rvpf5cea.jpeg?q=70",
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThEuqEkKVlX-SYQsJck_7gLcivEBLAvy032YSzqPUsC0t3BZnocyU5h-pSpfZ5_bOtHQ4&usqp=CAU",
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnYkI6CR3ucKij6GxW5lxYxrv3lICHanBppMwiKnaZ9KWvbCKjnN91VlH2DggZ5NH2qU8&usqp=CAU",
        ],
        sellingPrice: "4999",
        disPrice: "1845",
        disPrsent: "63%",
        soldBy: "SHOPPEEN",
        COD: "Available",
        Status: "In-Stock",
        quantity: "1",
        Size: ["S", "M", "L", "XL", "XXL"],
        ProductDetails: {
          productCode: "SHSDDAMA1336A686",
          idealFor: "Women",
          packOf: "1",
          occasion: "Festive, Party wear",
          fabric: "RangoliSilk",
        },
      },

      {
        title:
          "Printed, Self Design, Embellished, Floral Print, Solid/Plain Bollywood Georgette Saree  (Multicolor, Cream)",
        Image: [
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSryZyFqFxLHGZtZ3DZnFIz8N0ww33honSJJv_PbOBt0Bkyo9z0ZXLDXl0Igbv1q12s2DA&usqp=CAU",
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPR0EKN2Dj6sxQy3vS9XtIasss2-2XakVX8lhHzowfqosKYfD551ZReFRsL4SO9vTnzz0&usqp=CAU",
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTKf-UPGAZsxdw3LB4iQalrPrOUSWtlMiHjhOyzgt5zvYDKH5sFJaZMTa-KPXh4cd49VI&usqp=CAU",
        ],
        sellingPrice: "5799",
        disPrice: "2100",
        disPrsent: "63%",
        soldBy: "SHOPPEEN",
        COD: "Available",
        Status: "In-Stock",
        quantity: "1",
        Size: ["S", "M", "L", "XL", "XXL"],
        ProductDetails: {
          productCode: "SHSDDFV1452A687",
          idealFor: "Women",
          packOf: "1",
          occasion: "Wedding Wear,Party Wear",
          fabric: "Half velvet half viscose",
        },
      },
      {
        title:
          "Self Design, Woven Kanjivaram Silk Blend, Jacquard Saree  (Green)",
        Image: [
          "https://rukminim1.flixcart.com/image/832/832/kmgn0cw0/sari/y/u/p/free-butta-butti-green-bplash-fashion-unstitched-original-imagfczyznwph2gy.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/kms2j680/sari/d/h/f/free-kanjivaramsareeslatestdesign-catwalk-studio-unstitched-original-imagfhyzqwvcw3bn.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/xif0q/shopsy-sari/w/m/a/free-shopsy-gola-green-02-benaifer-fashion-unstitched-original-imagfdtzezzbk3ha.jpeg?q=70",
        ],
        sellingPrice: "3999",
        disPrice: "829",
        disPrsent: "79%",
        soldBy: "SHOPPEEN",
        COD: "Available",
        Status: "In-Stock",
        quantity: "1",
        Size: ["S", "M", "L", "XL", "XXL"],
        ProductDetails: {
          productCode: "SHSDDSWAS1291A693",
          idealFor: "Women",
          packOf: "1",
          occasion: "Festive,Party Wear",
          fabric: "GermanSilk",
        },
      },
      {
        title: "Embellished, Solid/Plain Bollywood Lycra Blend Saree  (Brown)",
        Image: [
          "https://rukminim1.flixcart.com/image/400/400/kph8h3k0/sari/a/e/n/free-rw-red-shop-lady-stitched-original-imag3pfdbrhvazfw.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/400/400/kbl4cy80/sari/h/n/c/free-3002-radha-raman-fashion-unstitched-original-imafswhrrcshtgz7.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/832/832/krxtrww0/sari/j/0/h/free-malai-saree-carryox-unstitched-original-imag5mdhffez2dcz.jpeg?q=70",
        ],
        sellingPrice: "2645",
        disPrice: "2215",
        disPrsent: "16%",
        soldBy: "SHOPPEEN",
        COD: "Available",
        Status: "In-Stock",
        quantity: "1",
        Size: ["S", "M", "L", "XL", "XXL"],
        ProductDetails: {
          productCode: "SHSDDSIVELA674",
          idealFor: "Women",
          packOf: "1",
          occasion: "WeddingParty ,Party Wear",
          fabric: "MalaiVelvet",
        },
      },
      {
        title: "Embroidered Bollywood Net Saree  (Blue)",
        Image: [
          "https://rukminim1.flixcart.com/image/612/612/krxtrww0/sari/z/w/a/free-malai-saree-carryox-unstitched-original-imag5mdhgyf62pwf.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/krxtrww0/sari/u/5/n/free-malai-saree-carryox-unstitched-original-imag5mdhfnmavjwj.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/832/832/xif0q/sari/g/x/2/free-latest-new-design-net-saree-casual-formal-party-wear-original-imaggzs64jffmnmb.jpeg?q=70",
        ],
        sellingPrice: "6399",
        disPrice: "2395",
        disPrsent: "62%",
        soldBy: "SHOPPEEN",
        COD: "Available",
        Status: "In-Stock",
        quantity: "1",
        Size: ["S", "M", "L", "XL", "XXL"],
        ProductDetails: {
          productCode: "SHSDDPARI15O1A689",
          idealFor: "Women",
          packOf: "1",
          occasion: "WeddingParty ,Party Wear",
          fabric: "SoftGliterNet",
        },
      },

      {
        title:
          "Self Design, Woven Kanjivaram Silk Blend, Jacquard Saree  (Red)",
        Image: [
          "https://rukminim1.flixcart.com/image/612/612/kms2j680/sari/3/w/x/free-saree-for-women-catwalk-studio-unstitched-original-imagfhymf5ghms3z.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/x/n/s/free-bandhani-ruby-red-04-hathdora-creation-unstitched-original-imafz5sbhygxhrfh.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/832/832/kmgn0cw0/sari/0/e/l/free-butta-butti-red-bplash-fashion-unstitched-original-imagfczyatzagw5b.jpeg?q=70",
        ],
        sellingPrice: "3999",
        disPrice: "829",
        disPrsent: "79%",
        soldBy: "SHOPPEEN",
        COD: "Available",
        Status: "In-Stock",
        quantity: "1",
        Size: ["S", "M", "L", "XL", "XXL"],
        ProductDetails: {
          productCode: "SHSDDDHARAA692",
          idealFor: "Women",
          packOf: "1",
          occasion: "Festive ,Party Wear",
          fabric: "GermanSilk",
        },
      },
      {
        title:
          "Printed, Self Design, Hand Painted, Ombre, Graphic Print, Floral Print, Checkered Bollywood Georgette, Chiffon Saree  (Blue)",
        Image: [
          "https://rukminim1.flixcart.com/image/832/832/xif0q/sari/1/c/e/free-2691s255-samah-unstitched-original-imagkyhh57yvxscb.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/f/m/6/free-re-m-n-grey-richeraa-no-blouse-original-imagjyjjvzmmdc3d.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/z/f/8/free-ramuba-shani-ramuba-fab-unstitched-original-imagdyqyppghhqpm.jpeg?q=70",
        ],
        sellingPrice: "4599",
        disPrice: "599",
        disPrsent: "86%",
        soldBy: "SHOPPEEN",
        COD: "Available",
        Status: "In-Stock",
        quantity: "1",
        Size: ["S", "M", "L", "XL", "XXL"],
        ProductDetails: {
          productCode: "SHSDDDOL1543A695",
          idealFor: "Women",
          packOf: "1",
          occasion: "Festive ,Party Wear",
          fabric: "ChinonSilk",
        },
      },
      {
        title: "Solid/Plain Bollywood Georgette, Satin Saree  (Grey)",
        Image: [
          "https://rukminim1.flixcart.com/image/832/832/k4irzbk0/sari/f/f/n/free-ght6yh-sareeflame-original-imafh3qjge4uehs7.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/g/1/c/free-janki-nipshya-unstitched-original-image5wazpsjdmwh.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/e/d/x/free-ramuba-shani-ramuba-fab-unstitched-original-imagdyqytfpvnxmn.jpeg?q=70",
        ],
        sellingPrice: "5999",
        disPrice: "635",
        disPrsent: "89%",
        soldBy: "SHOPPEEN",
        COD: "Available",
        Status: "In-Stock",
        quantity: "1",
        Size: ["S", "M", "L", "XL", "XXL"],
        ProductDetails: {
          productCode: "SHSDDVOLVO1391A677",
          idealFor: "Women",
          packOf: "1",
          occasion: "Wedding Wear ,Party Wear",
          fabric: "PureGeorgette",
        },
      },
      {
        title: "Woven Kanjivaram Jacquard, Art Silk Saree  (Multicolor)",
        Image: [
          "https://rukminim1.flixcart.com/image/612/612/xif0q/shopsy-sari/c/v/n/free-catlog055net2023-hutah-unstitched-original-imagntjczfghzdpj.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/400/400/l4n2oi80/kurta/1/j/4/l-khan08-grn-kurta-khawab-fashion-original-imagfhshhfmnhpgd.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/832/832/xif0q/sari/v/v/r/free-jf-bahurani-copper-tereza-unstitched-original-imagczh7vd2vumdz.jpeg?q=70",
        ],
        sellingPrice: "2799",
        disPrice: "359",
        disPrsent: "87%",
        soldBy: "SHOPPEEN",
        COD: "Available",
        Status: "In-Stock",
        quantity: "1",
        Size: ["S", "M", "L", "XL", "XXL"],
        ProductDetails: {
          productCode: "SHSDDZOM1443A694",
          idealFor: "Women",
          packOf: "1",
          occasion: " Wedding Wear ,Party Wear",
          fabric: "NylonSilk",
        },
      },
      {
        title: "Embroidered Bollywood Net Saree  (Orange)",
        Image: [
          "https://rukminim1.flixcart.com/image/612/612/kz3118w0/sari/5/k/a/free-women-s-new-latest-women-s-soft-net-saree-with-embroidary-original-imagajuzgfvnteuq.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/kp2y2kw0/sari/t/h/c/free-peach-colour-net-saree-ethnic-desi-color-colour-reversible-original-imag3ecm7xyqvszr.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/832/832/kxjav0w0/sari/s/p/h/free-sk-orange-heavy-pure-mono-soft-net-hathdora-creation-original-imag9ynvgmkngrrg.jpeg?q=70",
        ],
        sellingPrice: "1999",
        disPrice: "749",
        disPrsent: "62%",
        soldBy: "SHOPPEEN",
        COD: "Available",
        Status: "In-Stock",
        quantity: "1",
        Size: ["S", "M", "L", "XL", "XXL"],
        ProductDetails: {
          productCode: "SHSDDRINA1485A675",
          idealFor: "Women",
          packOf: "1",
          occasion: "Wedding Wear ,Party Wear",
          fabric: "SoftNet",
        },
      },
      {
        title: "Solid/Plain Assam Silk Pure Silk Saree  (Maroon)",
        Image: [
          "https://rukminim1.flixcart.com/image/832/832/xif0q/shopsy-sari/v/r/h/free-savariya-wine-kara-enterprise-no-blouse-original-imaghhzzepxqrszm.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/kyxb9u80/sari/g/o/i/free-malay-style-riddhi-enterprise-unstitched-original-imagbfu2be352dff.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/ki96c280-0/sari/7/m/c/free-ruffle-digital-patta-malai-aaena-stitched-original-imafy39uqhqvreuw.jpeg?q=70",
        ],
        sellingPrice: "3900",
        disPrice: "599",
        disPrsent: "84%",
        soldBy: "SHOPPEEN",
        COD: "Available",
        Status: "In-Stock",
        quantity: "1",
        Size: ["S", "M", "L", "XL", "XXL"],
        ProductDetails: {
          productCode: "SHSDDIGA690",
          idealFor: "Women",
          packOf: "1",
          occasion: "Wedding Wear ,Party Wear",
          fabric: "MalaiSilk",
        },
      },
      {
        title: "Embellished Bollywood Art Silk, Chiffon Saree  (Grey, Yellow)",
        Image: [
          "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/v/w/2/free-10-royal-opara-silk-saree-pure-cotton-sarees-for-summer-original-imagnx8k9h8vdvua.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/832/832/xif0q/sari/e/p/k/free-yellow-grey-half-half-atila-9-dailywear04-designer-stylist-original-imagkfm4bf6sfpfu.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/f/h/y/free-yellow-grey-half-half-atila-11-dailywear04-designer-stylist-original-imagkfmmnauxhy4k.jpeg?q=70",
        ],
        sellingPrice: "3599",
        disPrice: "749",
        disPrsent: "79%",
        soldBy: "SHOPPEEN",
        COD: "Available",
        Status: "In-Stock",
        quantity: "1",
        Size: ["S", "M", "L", "XL", "XXL"],
        ProductDetails: {
          productCode: "SHSDDSIRBORA673",
          idealFor: "Women",
          packOf: "1",
          occasion: "Wedding Wear ,Party Wear",
          fabric: "CrapeSilk",
        },
      },
      {
        title: "Woven Kanjivaram Silk Blend, Jacquard Saree  (Yellow)",
        Image: [
          "https://rukminim1.flixcart.com/image/832/832/kst9gnk0/sari/t/z/j/free-ms-106-faxofab-unstitched-original-imag6as6uwyyfe45.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/g/9/g/free-2837s296j-siril-unstitched-original-imagnhrnvprhvykw.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/0/c/r/free-esc-8177-anjaneya-sarees-unstitched-original-imagf8uuf3hugmua.jpeg?q=70",
        ],
        sellingPrice: "2499",
        disPrice: "849",
        disPrsent: "66%",
        soldBy: "SHOPPEEN",
        COD: "Available",
        Status: "In-Stock",
        quantity: "1",
        Size: ["S", "M", "L", "XL", "XXL"],
        ProductDetails: {
          productCode: "SHSDDSINA685",
          idealFor: "Women",
          packOf: "1",
          occasion: "Wedding Wear ,Party Wear",
          fabric: "ChinonSilk",
        },
      },

      {
        title: "Printed Bollywood Pure Silk Saree  (Blue)",
        Image: [
          "https://rukminim1.flixcart.com/image/612/612/kk01pjk0/sari/2/8/2/free-premium-quality-orange-red-yellow-fabric-ideal-for-daily-original-imafzftuyss3zgvk.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/kk01pjk0/sari/2/s/h/free-mq-japan-black-mess-up-fashion-unstitched-original-imafzfs7v47frdbp.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/kk01pjk0/sari/h/w/p/free-premium-quality-orange-red-yellow-fabric-ideal-for-daily-original-imafzftvzbyvfzhc.jpeg?q=70",
        ],
        sellingPrice: "2099",
        disPrice: "502",
        disPrsent: "76%",
        soldBy: "SHOPPEEN",
        COD: "Available",
        Status: "In-Stock",
        quantity: "1",
        Size: ["S", "M", "L", "XL", "XXL"],
        ProductDetails: {
          productCode: "SHSDDMISS134OA682",
          idealFor: "Women",
          packOf: "1",
          occasion: "Wedding Wear ,Party Wear",
          fabric: "JapanSilk",
        },
      },
    ],
  },
];

const Swaiper = [
  {
    title: "Sarees",
    Image:
      "https://dnpp799vut9mj.cloudfront.net/filters:format(webp)/dWcyiFc8FHL1DvJm98Lvv-gift.png",
    Productlist: [
      {
        title: "BOLLYWOOD SAREE JI MAIDAM SUMITHA SILK COTTON",
        Image: [
          "https://rukminim1.flixcart.com/image/612/612/kn97te80/sari/l/d/n/free-1068-k-shaibo-saree-unstitched-original-imagfz7jpaquwduy.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/kzygpzk0/sari/b/3/p/free-2329s781-samah-unstitched-original-imagbugfqwbxpsj2.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/kzrbiq80/sari/j/4/d/free-mk-zal-cosbila-fashion-unstitched-original-imagbpgmfvx7cehu.jpeg?q=70",
        ],
        sellingPrice: "2399",
        disPrice: "890",
        disPrsent: "63%",
        soldBy: "SHOPPEEN",
        COD: "Available",
        status: "In-stock",
        quantity: "1",
        Size: ["S", "M", "L", "XL", "XXL"],
        ProductDetails: {
          productcode: "SHSJMSSA707",
          idealfor: "Women",
          packof: "1",
          Fabric: "Silk cotton",
          febricCare: "Hand Wash , Machine Wash",
        },
      },
    ],
    Productlist: [
      {
        title: "FANCY SAREE MANTRA FALAK GEORGETTE",
        Image: [
          "https://rukminim1.flixcart.com/image/612/612/kv9urgw0/sari/2/x/v/free-dl-5-blue-desty-unstitched-original-imag87hgkf8zvyqq.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/kzvlua80/sari/7/s/l/free-sds0030-sadika-unstitched-original-imagbsg4na5x3gfn.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/krkyt8w0/sari/y/p/v/free-wedding-saree-ecolors-fab-unstitched-original-imag5c8efuhrjz9t.jpeg?q=70",
        ],
        sellingPrice: "2303",
        disPrice: "995",
        disPrsent: "57%",
        soldBy: "SHOPPEEN",
        COD: "Available",
        status: "In-stock",
        quantity: "1",
        Size: ["S", "M", "L", "XL", "XXL"],
        ProductDetails: {
          productcode: "SHSMANFALAK1002A11",
          idealfor: "Women",
          packof: "1",
          Fabric: "Georgette",
          febricCare: "Hand Wash , Machine Wash",
        },
      },
    ],
    Productlist: [
      {
        title: "BOLLYWOOD SAREE JI MAIDAM FACE PRINT (MULTI COLOR)",
        Image: [
          "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/d/y/m/free-blstin1-blissta-unstitched-original-imaghy4a6hgghcc8.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/r/v/c/free-at-kl-101-aarvi-trends-unstitched-original-imagkcdxgjsxfrv2.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/kqv8vww0/sari/w/h/i/free-mansi-saree-yellow-vajiba-unstitched-original-imag4sdzncyfvsx3.jpeg?q=70",
        ],
        sellingPrice: "2624",
        disPrice: "1100",
        disPrsent: "58%",
        soldBy: "SHOPPEEN",
        COD: "Available",
        status: "In-stock",
        quantity: "1",
        Size: ["S", "M", "L", "XL", "XXL"],
        ProductDetails: {
          productcode: "SHSJMFPA716",
          idealfor: "Women",
          packof: "1",
          Fabric: "Satin",
          febricCare: "Hand Wash , Machine Wash",
        },
      },
    ],

    Productlist: [
      {
        title: "BOLLYWOOD SAREE DHRUV FASHION DF-FADDING GEORGETTE",
        Image: [
          "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/u/j/4/free-8101-1-kashvi-sarees-unstitched-original-imagn22qhe7wgmz7.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/n/u/d/free-bfgrt145-surat4fashion-unstitched-original-imaghv4whzwz7yav.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/xif0q/sari/z/t/s/free-gulab-new-saree-anjavi-fashion-unstitched-original-imag7pw9skh8hneb-bb.jpeg?q=70",
        ],
        sellingPrice: "2034",
        disPrice: "1149",
        disPrsent: "59%",
        soldBy: "SHOPPEEN",
        COD: "Available",
        status: "In-stock",
        quantity: "1",
        Size: ["S", "M", "L", "XL", "XXL"],
        ProductDetails: {
          productcode: "SHSDFFADA704",
          idealfor: "Women",
          packof: "1",
          Fabric: "Georgette",
          febricCare: "Hand Wash",
        },
      },
    ],
    Productlist: [
      {
        title: "BOLLYWOOD SAREE DHRUV FASHION DF-3231 GEORGETTE",
        Image: [
          "https://rukminim1.flixcart.com/image/612/612/k4rcmfk0pkrrdj/sari/v/a/6/free-black-1466-6-pooja-fashion-1466-6-original-imafd5zbedgzeps9.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/kay9bbk0/sari/a/s/z/free-1262-5-kashvi-sarees-unstitched-original-imafsepbpnpbxgsz.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/kzd147k0/sari/y/t/f/free-neavyblue-saree-lyunica-unstitched-original-imagbe5hxufrqb5d.jpeg?q=70",
        ],
        sellingPrice: "2999",
        disPrice: "1274",
        disPrsent: "58%",
        soldBy: "SHOPPEEN",
        COD: "Available",
        status: "In-stock",
        quantity: "1",
        Size: ["S", "M", "L", "XL", "XXL"],
        ProductDetails: {
          productcode: "SHSDF3231A703",
          idealfor: "Women",
          packof: "1",
          Fabric: "Georgette",
          febricCare: "Hand Wash",
        },
      },
    ],
  },
  {
    title: "Popcorn Pants",
    Image:
      "https://dnpp799vut9mj.cloudfront.net/filters:format(webp)/dWcyiFc8FHL1DvJm98Lvv-Gift_2.png",
    Productlist: [
      {
        title: "POPCORN PANT PURPLE GRAPES MATT BLACK",
        Image: [
          "https://rukminim1.flixcart.com/image/612/612/xif0q/jean/r/a/b/38-eps-black-03-urbano-fashion-original-imaghkgk27whjcej.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/xif0q/jean/h/y/d/28-1-eps-black-06-urbano-fashion-original-imafumyf4fxzhduu-bb.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/kdbzqfk0/jean/q/8/3/36-mpszipjean-black-urbano-fashion-original-imafu9hqhqzyhrng.jpeg?q=70",
        ],
        sellingPrice: "1699",
        disPrice: "470",
        disPrsent: "72%",
        soldBy: "SHOPPEEN",
        COD: "Available",
        status: "In-stock",
        quantity: "1",
        Size: [28, 30, 36, 38],
        ProductDetails: {
          productcode: "SHTPGPPA508",
          idealfor: "Men",
          packof: "1",
          Fabric: "Lycra",
          febricCare: "Hand Wash , Machine Wash",
        },
      },
    ],
    Productlist: [
      {
        title: "POPCORN PANT PURPLE GRAPES CREAM",
        Image: [
          "https://rukminim1.flixcart.com/image/612/612/xif0q/trouser/l/b/v/32-kpb-67-cpslmft-crm-killer-original-imaghza3cpwfbpzu.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/kqwobrk0/trouser/e/4/b/34-dominoslycra-darkcream-13-haul-chic-original-imag4tk4e3sfvhzb.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/kzegk280/trouser/z/o/b/28-t933-merge-chex-flexi-cream-aa-ad-av-original-imagbf78fynh4jzb.jpeg?q=70",
        ],
        sellingPrice: "1699",
        disPrice: "485",
        disPrsent: "71%",
        soldBy: "SHOPPEEN",
        COD: "Available",
        status: "In-stock",
        quantity: "1",
        Size: [28, 32, 34],
        ProductDetails: {
          productcode: "SHTPGPPA499",
          idealfor: "Men",
          packof: "1",
          Fabric: "Lycra",
          febricCare: "Hand Wash , Machine Wash",
        },
      },
    ],
    Productlist: [
      {
        title: "POPCORN PANT PURPLE GRAPES GREEN",
        Image: [
          "https://rukminim1.flixcart.com/image/612/612/xif0q/trouser/g/3/g/32-pro-ss-pg-provogue-original-imaghhsbehfzduwn.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/xif0q/trouser/c/a/e/36-g-1-bapasitaram-enterprise-original-imagkybyzqyqcxab.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/xif0q/trouser/y/d/n/34-tpnw1-topqore-original-imagbz842hnufgxg-bb.jpeg?q=70",
        ],
        sellingPrice: "1549",
        disPrice: "475",
        disPrsent: "69%",
        soldBy: "SHOPPEEN",
        COD: "Available",
        status: "In-stock",
        quantity: "1",
        Size: [32, 34, 36],
        ProductDetails: {
          productcode: "SHTPGPPA506",
          idealfor: "Men",
          packof: "1",
          Fabric: "Lycra",
          febricCare: "Hand Wash , Machine Wash",
        },
      },
    ],
    Productlist: [
      {
        title: "POPCORN PANT PURPLE GRAPES CEMENT",
        Image: [
          "https://rukminim1.flixcart.com/image/612/612/xif0q/trouser/q/p/k/32-g-1-gaumukhi-creation-original-imaghf5haa6wdqnz.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/xif0q/trouser/7/r/n/28-t-1-fashionable-village-original-imaghevjdzwr47r9.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/xif0q/trouser/t/z/q/38-oldcs-medium-grey-franko-roger-original-imaghhvnybubx3d7.jpeg?q=70",
        ],
        sellingPrice: "1549",
        disPrice: "509",
        disPrsent: "67%",
        soldBy: "SHOPPEEN",
        COD: "Available",
        status: "In-stock",
        quantity: "1",
        Size: [28, 32, 38],
        ProductDetails: {
          productcode: "SHTPGPPA500",
          idealfor: "Men",
          packof: "1",
          Fabric: "Lycra",
          febricCare: "Hand Wash , Machine Wash",
        },
      },
    ],
    Productlist: [
      {
        title: "POPCORN PANT PURPLE GRAPES WINE",
        Image: [
          "https://rukminim1.flixcart.com/image/612/612/xif0q/trouser/r/p/m/30-trouser-solid-01-gaumukhi-creation-original-imaghbxye6pkbbk5.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/xif0q/trouser/1/p/t/36-g-1-gaumukhi-creation-original-imaghdg7cxu7mgnv.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/xif0q/trouser/r/p/m/30-trouser-solid-01-gaumukhi-creation-original-imaghbxye6pkbbk5.jpeg?q=70",
        ],
        sellingPrice: "1699",
        disPrice: "485",
        disPrsent: "71%",
        soldBy: "SHOPPEEN",
        COD: "Available",
        status: "In-stock",
        quantity: "1",
        Size: [28, 30, 32, 34, 36],
        ProductDetails: {
          productcode: "SHTPGPPA507",
          idealfor: "Men",
          packof: "1",
          Fabric: "Lycra",
          febricCare: "Hand Wash , Machine Wash",
        },
      },
    ],
  },
  {
    title: "Jeans",
    Image:
      "https://dnpp799vut9mj.cloudfront.net/filters:format(webp)/dWcyiFc8FHL1DvJm98Lvv-06.jpg  ",
    Productlist: [
      {
        title: "JEANS PURPLE GRAPES DENIM BLUE",
        Image: [
          "https://rukminim1.flixcart.com/image/612/612/xif0q/jean/p/g/p/32-bmw-darklevis-d-ben-martin-original-imafszrthheg5usf-bb.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/k0wqwsw0/jean/d/c/h/30-10064495-roadster-original-imafkhymuff6j95d.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/xif0q/jean/n/b/0/28-jns-light-grey-ben-martin-original-imafszrt6f9qgvym-bb.jpeg?q=70",
        ],
        sellingPrice: "1999",
        disPrice: "855",
        disPrsent: "57%",
        soldBy: "SHOPPEEN",
        COD: "Available",
        status: "In-stock",
        quantity: "1",
        Size: [28, 30, 32, 34],
        ProductDetails: {
          productcode: "SHTPGJA7A442",
          idealfor: "Men",
          packof: "1",
          Fabric: "Denim",
          febricCare: "Machine Wash",
        },
      },
    ],
    Productlist: [
      {
        title: "JEANS PURPLE GRAPES BLACK SHADE ",
        Image: [
          "https://rukminim1.flixcart.com/image/612/612/xif0q/trouser/b/z/k/36-tp4qset05blak-36-dream-makers-original-imafk5gtmhbenjhs-bb.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/xif0q/jean/j/c/o/34-word-styzon-original-imafxxnggvb4zcfb-bb.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/xif0q/jean/m/r/l/34-r-280-styzon-original-imagggzszjygbgy7.jpeg?q=70",
        ],
        sellingPrice: "1999",
        disPrice: "735",
        disPrsent: "63%",
        soldBy: "SHOPPEEN",
        COD: "Available",
        status: "In-stock",
        quantity: "1",
        Size: [28, 30, 32, 34, 36],
        ProductDetails: {
          productcode: "SHTPGJA4A439",
          idealfor: "Men",
          packof: "1",
          Fabric: "Denim",
          febricCare: "Machine Wash",
        },
      },
    ],
    Productlist: [
      {
        title: "JEANS YES BRAND SQUARE DESIGN DENIM BLUE",
        Image: [
          "https://rukminim1.flixcart.com/image/612/612/xif0q/jean/5/r/u/38-ecskn-bb-15-lightblue-blue-buddha-original-imagh7dgydg2ztm5.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/kn4xhu80/jean/n/t/e/32-19p4l23r1145i-901-united-colors-of-benetton-original-imagfvwzsfvnkq9p.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/kbb49zk0/jean/n/b/u/36-bmw-darklevis-d-ben-martin-original-imafszrtctdhcqe2.jpeg?q=70",
        ],
        sellingPrice: "1999",
        disPrice: "840",
        disPrsent: "58%",
        soldBy: "SHOPPEEN",
        COD: "Available",
        status: "In-stock",
        quantity: "1",
        Size: [28, 30, 32, 36, 38],
        ProductDetails: {
          productcode: "SHTYBJFSHDNCLA361",
          idealfor: "Men",
          packof: "1",
          Fabric: "Denim",
          febricCare: "Hand Wash , Machine Wash",
        },
      },
    ],
    Productlist: [
      {
        title: "JEANS YES BRAND FASHION LIGHT BLUE",
        Image: [
          "https://rukminim1.flixcart.com/image/612/612/jgcktjk0/jean/z/s/d/32-fmjn3949blue-flying-machine-original-imaf4huxqfkmf86j.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/xif0q/jean/n/b/0/28-jns-light-grey-ben-martin-original-imafszrt6f9qgvym-bb.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/kw6pw280/jean/l/r/6/36-hljn001959-highlander-original-imag8wwhdggkbhf6.jpeg?q=70",
        ],
        sellingPrice: "2399",
        disPrice: "882",
        disPrsent: "63%",
        soldBy: "SHOPPEEN",
        COD: "Available",
        status: "In-stock",
        quantity: "1",
        Size: [28, 30, 32, 34, 36],
        ProductDetails: {
          productcode: "SHTYBJFASA392",
          idealfor: "Men",
          packof: "1",
          Fabric: "Denim",
          febricCare: "Machine Wash",
        },
      },
    ],
    Productlist: [
      {
        title: " JEANS YES BRAND FASHION BLUE",
        Image: [
          "https://rukminim1.flixcart.com/image/612/612/k41mp3k0/jean/6/b/5/40-avwhskryelstrpbwr-mblu-01-urbano-fashion-original-imafmzyghsq9gvy6.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/kj7gwi80hlty2aw-0/jean/u/r/c/34-1-avdisheavywhsk-mblu-urbano-fashion-original-imafyyahbsng4uuq.jpeg?q=70",
          "https://rukminim1.flixcart.com/image/612/612/xif0q/jean/9/w/y/28-avdisheavywhsk-iceblu-urbano-fashion-original-imaghzq7js7tzzpg.jpeg?q=70",
        ],
        sellingPrice: "2399",
        disPrice: "889",
        disPrsent: "63%",
        soldBy: "SHOPPEEN",
        COD: "Available",
        status: "In-stock",
        quantity: "1",
        Size: [28, 30, 34, 38, 40],
        ProductDetails: {
          productcode: "SHTYBJFASA394",
          idealfor: "Men",
          packof: "1",
          Fabric: "Denim",
          febricCare: "Hand Wash , Machine Wash",
        },
      },
    ],
  },
];

module.exports = {
  Categories,
  FashionSareeCollections,
  Swaiper,
};
